name: mruby/edge CI

on:
  push:
    branches:
      - master
    paths:
      - 'mrubyedge/**'
  pull_request:
    branches:
      - master
    paths:
      - 'mrubyedge/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install C compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run mruby/edge tests
        run: cargo test
        working-directory: mrubyedge

      - name: Build
        run: cargo build --release
        working-directory: mrubyedge